dataset: mocap
data_path: ../../../datasets/MaBe/mouse

num_classes: 2
num_workers: 4
feats_size: 512

training:
  lr: 5e-4
  num_epochs: 100
  weight_decay: 1e-4
  optimizer: adamw
  batch_size: 32
  seed: 0

model:
  embed: 128
  dropout_patch: 0.5
  dropout_node: 0.2

hardware:
  gpu_index: [0]

logging:
  save_dir: ./savemodel/
  epoch_des: 10

data:
  if_interval: false
  instance_len: 30
  if_extract_feature: false