model:
  in_dim: 128
  n_hiddens: 128
  n_residual_hiddens: 64
  n_residual_layers: 1
  embedding_dim: 64
  n_embeddings: 100
  beta: 0.25

data:
  dataset: mabe_mouse
  path_to_data_dir: /home/rguo_hpc/myfolder/code/pipeline/pretrain/models/BehaveMAE/outputs/mice/experiment/submission_1.npy
  num_frames: 300
  sliding_window: 1
  sampling_rate: 1
  if_fill_holes: false
  patch_size: [3, 1, 24]
  compression_factor: 4

augmentation:
  data_augment: true
  centeralign: false
  include_testdata: false

dataloader:
  num_workers: 8
  pin_mem: false

training:
  batch_size: 32
  n_updates: 5200
  learning_rate: 0.002

logging:
  log_interval: 50

paths:
  save_dir: ./outputs/
  ckpt_path: ./outputs/models/vqvae_model.pth

job:
  type: train  # options: train, compute_representations